spring:
  application:
    name : password-manager 
  datasource:
    url: jdbc:postgresql://localhost:15432/client-db
    username: phatdo
    password: bimatnha
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 137288479135-nqhdl93ll5h2vfq29j79s05r21vi24pl.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile 
        provider: 
          google:
            token-uri: https://oauth2.googleapis.com/token
logging:
  level:
    org:
      springframework:
        security: DEBUG