spring:
  application:
    name : password-manager 
  datasource:
    url: jdbc:postgresql://localhost:15432/client-db
    username: phatdo
    password: bimatnha
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: {clientId}
            client-secret: {clientSecret}
            redirect-uri: http://localhost:8080/{callback}
            scope:
              - email
              - profile 
              - openid